// frame/src/app/App.tsx
import { getCurrentWindow } from "@tauri-apps/api/window";
import { onCleanup, onMount } from "solid-js";
import { Launcher } from "../features/launcher/Launcher";
import { commands } from "../ipc/bindings";
import * as tabs from "../state/tabs";
import * as theme from "../state/theme";
import * as ui from "../state/ui";
import { Shell } from "./Shell";

const IS_MAC = navigator.userAgent.includes("Mac");

// The chrome webview consumes these before any native menu sees them (WebKit
// focus keys on macOS; no menu bar exists at all on Windows/Linux), so the
// chrome re-routes them onto the shared command entry.
const CHROME_KEYS: Array<[match: (e: KeyboardEvent) => boolean, command: string]> = [
  [(e) => e.ctrlKey && !e.shiftKey && e.key === "Tab", "tab.next"],
  [(e) => e.ctrlKey && e.shiftKey && e.key === "Tab", "tab.previous"],
];

if (!IS_MAC) {
  const plain: Array<[string, string]> = [
    ["t", "tab.new"],
    ["w", "tab.close"],
    ["r", "nav.reload"],
    ["l", "url.focus"],
    ["=", "zoom.in"],
    ["-", "zoom.out"],
    ["0", "zoom.reset"],
    ["[", "nav.back"],
    ["]", "nav.forward"],
    [".", "nav.stop"],
  ];
  for (const [key, command] of plain) {
    CHROME_KEYS.push([
      (e) => e.ctrlKey && !e.shiftKey && !e.altKey && e.key.toLowerCase() === key,
      command,
    ]);
  }
}

function onKeyDown(e: KeyboardEvent) {
  for (const [match, command] of CHROME_KEYS) {
    if (match(e)) {
      e.preventDefault();
      void commands.runCommand(command);
      return;
    }
  }
}

export default function App() {
  onMount(() => {
    void theme.init();
    onCleanup(() => theme.dispose());
  });

  if (getCurrentWindow().label === "panel") {
    return <Launcher />;
  }

  onMount(() => {
    void tabs.init();
    void ui.init();
    document.addEventListener("keydown", onKeyDown);
    onCleanup(() => {
      tabs.dispose();
      ui.dispose();
      document.removeEventListener("keydown", onKeyDown);
    });
  });
  return <Shell />;
}

// frame/src/app/App.svelte
<script lang="ts">
  import { getCurrentWindow } from "@tauri-apps/api/window";
  import { onMount } from "svelte";
  import Launcher from "../features/launcher/Launcher.svelte";
  import Dividers from "../features/split/Dividers.svelte";
  import { commands } from "../ipc/bindings";
  import * as blocker from "../state/blocker.svelte";
  import * as layout from "../state/layout.svelte";
  import * as operations from "../state/operations";
  import * as runtime from "../state/runtime.svelte";
  import * as tabs from "../state/tabs.svelte";
  import * as theme from "../state/theme";
  import * as ui from "../state/ui.svelte";
  import Shell from "./Shell.svelte";

  const currentWindow = getCurrentWindow();
  const isPanel = currentWindow.label === "panel";
  const isMac = navigator.userAgent.includes("Mac");

  type ChromeShortcut = {
    matches: (event: KeyboardEvent) => boolean;
    command: string;
  };

  const chromeShortcuts: ChromeShortcut[] = [
    {
      matches: (event) => event.ctrlKey && !event.shiftKey && event.key === "Tab",
      command: "tab.next",
    },
    {
      matches: (event) => event.ctrlKey && event.shiftKey && event.key === "Tab",
      command: "tab.previous",
    },
  ];

  if (!isMac) {
    const primaryShortcuts: ReadonlyArray<readonly [string, string]> = [
      ["t", "tab.new"],
      ["w", "tab.close"],
      ["r", "nav.reload"],
      ["l", "url.focus"],
      ["=", "zoom.in"],
      ["-", "zoom.out"],
      ["0", "zoom.reset"],
      ["[", "nav.back"],
      ["]", "nav.forward"],
      [".", "nav.stop"],
    ];

    for (const [key, command] of primaryShortcuts) {
      chromeShortcuts.push({
        matches: (event) =>
          event.ctrlKey && !event.shiftKey && !event.altKey && event.key.toLowerCase() === key,
        command,
      });
    }
  }

  function handleKeydown(event: KeyboardEvent) {
    for (const shortcut of chromeShortcuts) {
      if (!shortcut.matches(event)) continue;
      event.preventDefault();
      void commands.runCommand(shortcut.command);
      return;
    }
  }

  onMount(() => {
    let disposed = false;

    // Each async initializer performs its synchronous setup before its first
    // await. In particular, tabs installs every scoped projection listener
    // before bootstrap can ask native code for a snapshot.
    const themeReady = theme.init();

    if (isPanel) {
      void themeReady.catch(() => {
        console.error("trusted UI initialization failed");
      });
      return () => {
        disposed = true;
        theme.dispose();
      };
    }

    // Runtime status is emitted by the same actor-ordered bootstrap that
    // supplies tabs, so its listener must exist before tabs starts bootstrap.
    const runtimeReady = runtime.init();
    const tabsReady = tabs.init();
    const uiEventsReady = ui.init();
    void operations.init();
    void blocker.init();
    if (!isMac) void layout.init();
    document.addEventListener("keydown", handleKeydown);

    void (async () => {
      try {
        await Promise.all([themeReady, runtimeReady, tabsReady, uiEventsReady]);
        if (disposed) return;

        // A hidden native window can suspend animation frames indefinitely.
        // Resolve style/layout synchronously before admitting native reveal.
        void document.documentElement.getBoundingClientRect();
        void getComputedStyle(document.body).backgroundColor;
        if (!(await commands.uiReady())) {
          throw new Error("native startup gate rejected UI");
        }
      } catch {
        // Native owns the fail-closed watchdog. Keep attacker-controlled page
        // data and native internals out of this static diagnostic.
        console.error("trusted UI initialization failed");
      }
    })();

    return () => {
      disposed = true;
      theme.dispose();
      operations.dispose();
      blocker.dispose();
      runtime.dispose();
      tabs.dispose();
      ui.dispose();
      if (!isMac) layout.dispose();
      document.removeEventListener("keydown", handleKeydown);
    };
  });
</script>

{#if isPanel}
  <Launcher />
{:else}
  <Shell />
  {#if !isMac}
    <Dividers />
  {/if}
{/if}
